<div class="post-pagination" data-ng-controller="IndexController">

    <div class="post-contents">
        <div class="post-item" data-dir-paginate="post in lastPosts | itemsPerPage: 10">
            <h4 class="post-title">{{post.title}}</h4>
            <p class="post-date">{{post.date}}</p>
            <img data-ng-if="post.image" class="post-img" src="{{post.image}}">
            <p class="post-description">{{post.description}}</p>
            <a href="/post/{{post.title}}" class="post-detail-link">Read more</a>
            <div class="post-separator"></div>
        </div>
        <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
    </div>

</div>