<div class="post-pagination">

    <div class="post-contents">
        <div class="post-item" data-dir-paginate="post in lastPosts | itemsPerPage: 10">
            <h1 class="post-title">{{post.title}}</h1>
            <p class="post-date">{{post.date}}</p>
            <div class="post-contents-image">
                <a href="/post/{{post.link}}"><img data-ng-if="post.image[0]" class="post-img" data-ng-src="{{post.image}}"></a>
            </div>
            <p class="post-description" data-ng-bind-html="post.description"></p>
            <a href="/post/{{post.link}}" class="post-detail-link">Read more</a>
            <div class="post-separator"></div>
            <div class="pagination-content">
                <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
            </div>

        </div>

    </div>

</div>