<div class="post-content" data-ng-controller="PostController">

    <h4>{{post.title}}</h4>
    <p>{{post.date}}</p>
    <div class="banner-block" data-ng-controller="BannerController">
        <div class="main-slide-animation non-draggable-image" data-ng-repeat="banner in post.image track by $index"  data-ng-hide="!isCurrentSlideIndex($index)" data-ng-swipe-right="nextSlide()" data-ng-swipe-left="prevSlide()">

            <img class="post-img" src="{{banner}}" alt="{post.title}}">
            <div data-ng-if="post.image.length>1" class="gallery-controller">
                <p class="next" data-ng-click="nextSlide()"> >> </p>
                <p class="prev" data-ng-click="prevSlide()"> << </p>
            </div>
        </div>
    </div>

    <!-- <img data-ng-if="post.image" class="post-img" data-ng-src="{{post.image}}"-->
    <div data-compile-template data-ng-bind-html="post.description"></div>

    <script>
        var postTitle = <?php echo json_encode($postTitle); ?>;
    </script>


    <div id="disqus_thread"></div>

    <script>


        /**
         * RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
         * LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
         */
        /*
         var disqus_config = function () {
         this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
         this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
         };
         */
        (function() { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');

            s.src = '//alisch.disqus.com/embed.js';

            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>

    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

</div>
